---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-data-pvc
  annotations:
    volume.beta.kubernetes.io/persistent-volume: gitlab.postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: manual
