---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab.gitlab
  namespace: gitlab
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /data/gitlab/gitlab
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - 8no
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab.redis
  namespace: gitlab
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /data/gitlab/redis
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - 8no
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab.postgres
  namespace: gitlab
spec:
  storageClassName: manual
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /data/gitlab/postgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - 8no
