---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-pvc
  annotations:
    volume.beta.kubernetes.io/persistent-volume: gitlab.redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
